databaseType = "PostgreSql"
id = "61c1501c-a365-4eae-bd85-08d04b7ba340"
name = "mlc-database"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.mlc-database]
url = "jdbc:postgresql://psql-mlc-database.postgres.database.azure.com:5432/postgres"
schemas = [ "public" ]
